[package]
name = "play-rinja"
version = "0.1.0"
edition = "2021"
publish = false
repository = "https://github.com/Kijewski/play-rinja"
license = "MIT OR Apache-2.0"

[dependencies]
rinja_derive_standalone = { version = "0.3.0", git = "https://github.com/rinja-rs/rinja", rev = "51c62435350937d119fc36a51083459cfb4f00ee", features = ["humansize", "num-traits", "serde_json", "urlencode"] }

prettyplease = "0.2.20"
proc-macro2 = { version = "1.0.86", default-features = false }
syn = { version = "2.0.72", default-features = false, features = ["full", "parsing", "printing"] }
web-sys = { version = "0.3.69", features = ["WorkerGlobalScope", "HtmlTextAreaElement", "Performance"] }
yew = { version = "0.21.0", features = ["csr"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = 0
panic = "abort"
