trunk-version = "^0.21.7"

[build]
target = "index.html"
dist = "dist"
public_url = "./"
inject_scripts = true
minify = "on_release"

[tools]
sass = "1.83.4"
wasm_bindgen = "0.2.100"
wasm_opt = "version_121"

[clean]
cargo = true
