trunk-version = "^0.21.4"

[build]
target = "index.html"
dist = "dist"
public_url = "./"
inject_scripts = true
minify = "on_release"

[tools]
sass = "1.83.0"
wasm_bindgen = "0.2.99"
wasm_opt = "version_121"

[clean]
cargo = true
